config/routes.rb
Rails.application.routes.draw do
  resources :manufacturers
  resources :products
  resources :attribute_sets
  resources :attributes

   root 'attributes#index'

end

app/models/attribute.rb
class Attribute < ActiveRecord::Base
    self.per_page = 10
    belongs_to :attribute_set, class_name:  "AttributeSet", foreign_key: 'attribute_set_id'
end

app/models/attribute_set.rb
class AttributeSet < ActiveRecord::Base
  has_many  :attr, class_name: "Attribute", foreign_key: 'attribute_set_id'
  has_many  :product, class_name: "Product", foreign_key: 'attribute_set_id'
  self.per_page = 10
end

app/models/product.rb
class Product < ActiveRecord::Base
  self.per_page = 10
  belongs_to :attribute_set, class_name: "AttributeSet", foreign_key: 'attribute_set_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attribute_sets_controller.rb
class AttributeSetsController < ApplicationController
  before_action :set_attribute_set, only: [:show, :edit, :update, :destroy]

  # GET /attribute_sets
  # GET /attribute_sets.json
  def index
    @attribute_sets = AttributeSet.paginate(:page => params[:page])
  end

  # GET /attribute_sets/1
  # GET /attribute_sets/1.json
  def show
    render json: @attribute_set
  end

  # GET /attribute_sets/new
  def new
    @attribute_set = AttributeSet.new
  end

  # GET /attribute_sets/1/edit
  def edit
  end

  # POST /attribute_sets
  # POST /attribute_sets.json
  def create
    @attribute_set = AttributeSet.new(attribute_set_params)

    respond_to do |format|
      if @attribute_set.save
        format.html { redirect_to @attribute_set, notice: 'Attribute set was successfully created.' }
        format.json { render :show, status: :created, location: @attribute_set }
      else
        format.html { render :new }
        format.json { render json: @attribute_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attribute_sets/1
  # PATCH/PUT /attribute_sets/1.json
  def update
    respond_to do |format|
      if @attribute_set.update(attribute_set_params)
        format.html { redirect_to @attribute_set, notice: 'Attribute set was successfully updated.' }
        format.json { render :show, status: :ok, location: @attribute_set }
      else
        format.html { render :edit }
        format.json { render json: @attribute_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attribute_sets/1
  # DELETE /attribute_sets/1.json
  def destroy
    @attribute_set.destroy
    respond_to do |format|
      format.html { redirect_to attribute_sets_url, notice: 'Attribute set was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attribute_set
      @attribute_set = AttributeSet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attribute_set_params
      params.require(:attribute_set).permit(:name, :legend_img_filename, :string)
    end
end

app/controllers/attributes_controller.rb
class AttributesController < ApplicationController
  before_action :set_attribute, only: [:show, :edit, :update, :destroy]

  # GET /attributes
  # GET /attributes.json
  def index
    @attributes = Attribute.paginate(:page => params[:page])
  end

  # GET /attributes/1
  # GET /attributes/1.json
  def show
  end

  # GET /attributes/new
  def new
    @attribute = Attribute.new
  end

  # GET /attributes/1/edit
  def edit
    @attribute_sets = AttributeSet.all
  end

  # POST /attributes
  # POST /attributes.json
  def create
    @attribute = Attribute.new(attribute_params)

    respond_to do |format|
      if @attribute.save
        format.html { redirect_to @attribute, notice: 'Attribute was successfully created.' }
        format.json { render :show, status: :created, location: @attribute }
      else
        format.html { render :new }
        format.json { render json: @attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attributes/1
  # PATCH/PUT /attributes/1.json
  def update
    respond_to do |format|
      if @attribute.update(attribute_params)
        format.html { redirect_to @attribute, notice: 'Attribute was successfully updated.' }
        format.json { render :show, status: :ok, location: @attribute }
      else
        format.html { render :edit }
        format.json { render json: @attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attributes/1
  # DELETE /attributes/1.json
  def destroy
    @attribute.destroy
    respond_to do |format|
      format.html { redirect_to attributes_url, notice: 'Attribute was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attribute
      @attribute = Attribute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attribute_params
      params.require(:attribute).permit(:id,
                                        :name,
                                        :data_type,
                                        :attribute_set_id, :null_allowed, :max_val, :json_name,
                                        :unit, :tolerance,:json_name, :idx_name,:min_val,
                                        :regex, :parent_id, :length, :scale, :length, :length_web,
                                        :scale_web,:is_critical_dimension, :seq_num, :tolerance,
                                        :null_display, :attribute_set_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json

  def index
    if not  params[:entity_name].nil?
      @products = Product.where(manfr_part_num:  params[:entity_name]).paginate(:page => params[:page])
    else
      @products = Product.paginate(:page => params[:page])
    end

  end

  def search
  end

  # GET /products/1
  # GET /products/1.json
  def show
     @product = Product.find(params[:id])
     @attributes = @product.attribute_set.attr
    render :json =>{
        product:  @product,
        attributes: @attributes,
        partType: @product.attribute_set.name
    }
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end


  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
     # @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:manfr_part_num, :name, :description, :attribute_set)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/attribute_sets/_form.html.erb
<%= form_for(@attribute_set) do |f| %>
  <% if @attribute_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attribute_set.errors.count, "error") %> prohibited this attribute_set from being saved:</h2>

      <ul>
      <% @attribute_set.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



    <%@attribute_set.attributes.each  do |key,value|%>
        <div class="form-group">
          <label for="<%=key%>"><%=key%></label>
          <input type="text" name="attribute_set[<%=key%>]" class="form-control" id="<%=key%>" value="<%=value%>">
        </div>
    <%end%>



  <div class="actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/attribute_sets/edit.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <h4>Edit Attribute Set</h4>
  </div>
</div>
<div class="row">
  <div class="col-lg-5 col-lg-offset-1 ">
    <%= render 'form' %>

    <%= link_to 'Show', @attribute_set %> |
    <%= link_to 'Back', attribute_sets_path %>
  </div>
  <div class="col-lg-5">
    <table class="table">
      <thead>
      <tr>
        <th>
          Attributes
        </th>
      </tr>
      </thead>
      <tbody>
      <% @attribute_set.attr.each do |a| %>
          <tr>
            <td><%= link_to  a.name, edit_attribute_path %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/attribute_sets/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-lg-2 col-lg-offset-4">
    <h4>Attribute Sets</h4>

  </div>
</div>
<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <table class="table">
      <thead>
      <tr>
        <th>Name</th>
        <th>Legend img filename</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @attribute_sets.each do |attribute_set| %>
          <tr>
            <td><%= link_to attribute_set.name, edit_attribute_set_path(attribute_set) %></td>
            <td><%= attribute_set.legend_img_filename %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Attribute set', new_attribute_set_path %>
    <div class="digg_pagination">
      <div class="page_info">
        <%= page_entries_info @attribute_sets %>
      </div>
      <%= will_paginate @attribute_sets, :container => false %>
    </div>
  </div>
</div>
  </div>
</div>

app/views/attribute_sets/new.html.erb
<h1>New Attribute Set</h1>

<%= render 'form' %>

<%= link_to 'Back', attribute_sets_path %>

app/views/attribute_sets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @attribute_set.name %>
</p>

<p>
  <strong>Legend img filename:</strong>
  <%= @attribute_set.legend_img_filename %>
</p>


<%= link_to 'Edit', edit_attribute_set_path(@attribute_set) %> |
<%= link_to 'Back', attribute_sets_path %>

app/views/attributes/_form.html.erb
<%= form_for(@attribute) do |f| %>
  <% if @attribute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attribute.errors.count, "error") %> prohibited this attribute from being saved:</h2>

      <ul>
      <% @attribute.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name,  :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :data_type %><br>
      <%= f.text_field :data_type,  :class => 'form-control' %>
    </div>
    <div class="form-group">
    <%=f.select  :attribute_set_id,
                 options_from_collection_for_select(@attribute_sets, "id", "name", :selected => @attribute.attribute_set_id), {}, :class => 'form-control selectpicker'%>
    </div>

    <div class="form-group">
      <%= f.label :idx_name %><br>
      <%= f.text_field :idx_name ,  :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :scale %><br>
      <%= f.number_field :scale ,  :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :scale_web %><br>
      <%= f.number_field :scale_web ,  :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :tolerance %><br>
      <%= f.number_field :tolerance ,  :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :length %><br>
      <%= f.number_field :length ,  :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :length_web %><br>
      <%= f.number_field :length_web ,  :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :unit %><br>
      <%= f.text_field :unit ,  :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :seq_num %><br>
      <%= f.number_field :seq_num ,  :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :null_allowed %><br>
      <%= f.check_box :null_allowed ,  :class => 'form-check-input' %>
    </div>

    <div class="form-group">
      <%= f.label :null_display %><br>
      <%= f.check_box :null_display ,  :class => 'form-check-input' %>
    </div>

    <div class="form-group">
      <%= f.label :is_critical_dimension %><br>
      <%= f.check_box :is_critical_dimension ,  :class => 'form-check-input' %>
    </div>


  <div class="actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/attributes/edit.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <h4>Editing Attribute</h4>
  </div>
</div>

<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <%= render 'form' %>

    <%= link_to 'Show', @attribute %> |
    <%= link_to 'Back', attributes_path %>
  </div>
</div>

app/views/attributes/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-lg-2 col-lg-offset-4">
    <h4>Attributes</h4>
  </div>
</div>
<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <table class="table">
      <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Data Type</th>
        <th>Attribute set</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @attributes.each do |attribute| %>
          <tr>
            <td><%= attribute.id %></td>
            <td><%=  link_to attribute.name, edit_attribute_path(attribute) %></td>
            <td><%= attribute.data_type %></td>
            <td><%= attribute.attribute_set_id %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Attribute', new_attribute_path %>

    <div class="digg_pagination">
      <div class="page_info">
        <%= page_entries_info @attributes %>
      </div>
      <%= will_paginate @attributes, :container => false %>
    </div>
  </div>
</div>

app/views/attributes/new.html.erb
<div class="row">
  <div class="col-lg-2 col-lg-offset-4">
    <h4>New Attribute</h4>
  </div>
</div>
<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <%= render 'form' %>
    <%= link_to 'Back', attributes_path %>
  </div>
</div>

app/views/attributes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @attribute.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @attribute.name %>
</p>

<p>
  <strong>Type value:</strong>
  <%= @attribute.type_value %>
</p>

<p>


<p>
  <strong>Attribute set:</strong>
  <%= @attribute.attribute_set_id %>
</p>



<%= link_to 'Edit', edit_attribute_path(@attribute) %> |
<%= link_to 'Back', attributes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  ng-app="TimmsApp">
<head>
  <title>Timms</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">TIMMS</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Entities <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/products">Products</a></li>
            <li><a href="/manufacturers">Manufacturers</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Properties <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/attributes">Attributes</a></li>
            <li><a href="/attribute_sets">Attribute Sets</a></li>

          </ul>
        </li>
      </ul>

      <form class="navbar-form navbar-left" action="/products" method="get">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
        <div class="form-group">
          <input type="text" class="form-control" id="entity_name" name="entity_name"  placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :manfr_part_num %><br>
    <%= f.text_field :manfr_part_num %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div ng-controller=" ProductEditController" ng-init="init()">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#part_details">Part Details</a></li>
        <li><a data-toggle="tab" href="#critical_dimensions">Critical Dimensions</a></li>
        <li><a data-toggle="tab" href="#turbo_types">Turbo Types</a></li>
        <li><a data-toggle="tab" href="#where_used">Where Used</a></li>
      </ul>

      <div class="tab-content">
        <div id="part_details" class="tab-pane fade in active" style="min-height: 200px">
          <table class="table">
            <thead>
            <tr>
              <th>
                Property
              </th>
              <th>
                Value
              </th>
            </tr>
            </thead>
            <tr>
              <td> Manufacture Part Number</td>
              <td> {{product.manfr_part_num}}</td>
            </tr>
            <tr>
              <td> Name</td>
              <td> {{product.name}}</td>
            </tr>
            <tr>
              <td> PartType</td>
              <td> {{partType}}</td>
            </tr>
            <tr>
              <td> Description</td>
              <td> {{product.description}}</td>
            </tr>
          </table>
        </div>
        <div id="critical_dimensions" class="tab-pane fade" style="min-height: 200px">
          <table class="table">
            <thead>
            <tr>
              <th>
                Name
              </th>
              <th>
                Value
              </th>
            </tr>
            </thead>
            <tr ng-repeat="attribute in attributes">
              <td>
                {{attribute.name}}
              </td>
              <td>
                {{product.critical_attributes[attribute.idx_name]}}
              </td>
            </tr>
          </table>
        </div>
        <div id="turbo_types" class="tab-pane fade" style="min-height: 200px">
          <table>
            <tr ng-repeat="t_type in product.turbo_type">
              <td>
                {{t_type}}
              </td>
            </tr>
          </table>
        </div>
        <div id="where_used" class="tab-pane fade" style="min-height: 200px" ng-include="'/templates/where_used.html'">

        </div>
      </div>
    </div>

    <div class="row" ng-include="'/templates/interchanges.html'">

    </div>

    <div class="row" ng-include="'/templates/bom.html'">


  </div>
</div>
</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-lg-2 col-lg-offset-4">
    <h4>Products</h4>
  </div>
</div>
<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <table class="table">
      <thead>
      <tr>
        <th>Manfr part num</th>
        <th>Name</th>
        <th>Description</th>
        <th>Attribute set Id</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @products.each do |product| %>
          <tr>
            <td><%= link_to product.manfr_part_num, edit_product_path(product) %></td>
            <td><%= product.name %></td>
            <td><%= product.description %></td>
            <td><%= product.attribute_set.name %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Product', new_product_path %>
    <div class="digg_pagination">
      <div class="page_info">
        <%= page_entries_info @products %>
      </div>
      <%= will_paginate @products, :container => false %>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Manfr part num:</strong>
  <%= @product.manfr_part_num %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>



<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>